//-----------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="AFS">
// Copyright (c) AFS. All rights reserved.
// </copyright>
//----------------------------------------------------------------------- 

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Netsy.Cache")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Netsy.DataModel.EtsyContext.#.ctor(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.EtsyContext.#BaseUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.Feedback.#ImageUrl25X25")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.Feedback.#Url")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.Feedbacks.#Results")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.Listing.#AllImages")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.Listing.#ImageUrl155X125")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.Listing.#ImageUrl200X200")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.Listing.#ImageUrl25X25")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.Listing.#ImageUrl430XN")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.Listing.#ImageUrl50X50")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.Listing.#ImageUrl75X75")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.Listing.#Materials")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "OutDate", Scope = "member", Target = "Netsy.DataModel.Listing.#SoldOutDate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.Listing.#Tags")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.Listing.#Url")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.ListingImage.#HsvColor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.ListingImage.#ImageUrl155X125")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.ListingImage.#ImageUrl200X200")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.ListingImage.#ImageUrl25X25")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.ListingImage.#ImageUrl430XN")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.ListingImage.#ImageUrl50X50")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.ListingImage.#ImageUrl75X75")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.Listings.#Results")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.Method.#Uri")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.MethodTable.#Results")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.PingResult.#Results")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.ServerEpoch.#Results")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.Shop.#BannerImageUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flag", Scope = "member", Target = "Netsy.DataModel.Shop.#IsVacationFlag")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.Shop.#Sections")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.Shops.#Results")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.StringResults.#Results")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.User.#ImageUrl25X25")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.User.#ImageUrl30X30")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.User.#ImageUrl50X50")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.User.#ImageUrl75X75")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.User.#Materials")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.User.#Url")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Netsy.DataModel.Users.#Results")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "Netsy.Helpers.StringHelpers.#ToStringLower(System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Netsy.Interfaces.IGiftService.#GetGiftGuides()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Netsy.Interfaces.IServerService.#GetMethodTable()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Netsy.Interfaces.IServerService.#GetServerEpoch()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Netsy.Interfaces.ITagCategoryService.#GetTopCategories()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Netsy.Interfaces.ITagCategoryService.#GetTopTags()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Netsy.Requests.RequestHelper.#StartRetrieve`1(System.Object,System.Uri,System.EventHandler`1<Netsy.Helpers.ResultEventArgs`1<!!0>>,Netsy.Cache.IDataCache)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Netsy.Requests.RequestHelper.#StartRetrieve`1(System.Object,System.Uri,System.EventHandler`1<Netsy.Helpers.ResultEventArgs`1<!!0>>,Netsy.Cache.IDataCache)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Netsy.Requests.RequestHelper.#TestCallPrerequisites`1(System.Object,System.EventHandler`1<Netsy.Helpers.ResultEventArgs`1<!!0>>,Netsy.DataModel.EtsyContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Netsy.Requests.RequestHelper.#TestSendEvent`1(System.EventHandler`1<Netsy.Helpers.ResultEventArgs`1<!!0>>,System.Object,Netsy.Helpers.ResultEventArgs`1<!!0>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Netsy.DataModel.Feedback.#ImageUrlFullXFull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Netsy.Requests.DataRetriever.#StartRetrieve`1(System.Uri,System.EventHandler`1<Netsy.Helpers.ResultEventArgs`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Netsy.Requests.DataRetriever.#StartRetrieve`1(System.Uri,System.EventHandler`1<Netsy.Helpers.ResultEventArgs`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Netsy.Requests.IDataRetriever.#StartRetrieve`1(System.Uri,System.EventHandler`1<Netsy.Helpers.ResultEventArgs`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Netsy.Requests.RequestHelper.SendError<T>(System.Object,System.EventHandler<Netsy.Helpers.ResultEventArgs<T>>,System.String)", Scope = "member", Target = "Netsy.Requests.RequestHelper.#TestOffsetLimit`1(System.Object,System.EventHandler`1<Netsy.Helpers.ResultEventArgs`1<!!0>>,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Netsy.Requests.RequestHelper.SendError<T>(System.Object,System.EventHandler<Netsy.Helpers.ResultEventArgs<T>>,System.String)", Scope = "member", Target = "Netsy.Requests.RequestHelper.#TestCallPrerequisites`1(System.Object,System.EventHandler`1<Netsy.Helpers.ResultEventArgs`1<!!0>>,Netsy.DataModel.EtsyContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Netsy.Requests.RequestHelper.SendError<Netsy.DataModel.Listings>(System.Object,System.EventHandler<Netsy.Helpers.ResultEventArgs<T>>,System.String)", Scope = "member", Target = "Netsy.Services.ListingsService.#GetListingsByTags(System.Collections.Generic.IEnumerable`1<System.String>,Netsy.DataModel.SortField,Netsy.DataModel.SortOrder,System.Int32,System.Int32,Netsy.DataModel.DetailLevel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Netsy.Requests.RequestHelper.SendError<Netsy.DataModel.Listings>(System.Object,System.EventHandler<Netsy.Helpers.ResultEventArgs<T>>,System.String)", Scope = "member", Target = "Netsy.Services.ListingsService.#GetListingsByMaterials(System.Collections.Generic.IEnumerable`1<System.String>,Netsy.DataModel.SortField,Netsy.DataModel.SortOrder,System.Int32,System.Int32,Netsy.DataModel.DetailLevel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Netsy.Requests.RequestHelper.SendError<Netsy.DataModel.Listings>(System.Object,System.EventHandler<Netsy.Helpers.ResultEventArgs<T>>,System.String)", Scope = "member", Target = "Netsy.Services.ListingsService.#GetListingsByKeyword(System.Collections.Generic.IEnumerable`1<System.String>,Netsy.DataModel.SortField,Netsy.DataModel.SortOrder,System.Nullable`1<System.Decimal>,System.Nullable`1<System.Decimal>,System.Boolean,System.Int32,System.Int32,Netsy.DataModel.DetailLevel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Netsy.Requests.RequestHelper.SendError<Netsy.DataModel.Listings>(System.Object,System.EventHandler<Netsy.Helpers.ResultEventArgs<T>>,System.String)", Scope = "member", Target = "Netsy.Services.ListingsService.#GetListingsByColorAndKeywords(System.Collections.Generic.IEnumerable`1<System.String>,Netsy.DataModel.EtsyColor,System.Int32,System.Int32,System.Int32,Netsy.DataModel.DetailLevel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Netsy.Requests.RequestHelper.#TestOffsetLimit`1(System.Object,System.EventHandler`1<Netsy.Helpers.ResultEventArgs`1<!!0>>,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Netsy.Requests.RequestHelper.#SendError`1(System.Object,System.EventHandler`1<Netsy.Helpers.ResultEventArgs`1<!!0>>,System.String)")]
